Special case when NaNs present in `min()` and `max()`
data-apis/array-api pull request #335
Opened 2021-11-15 10:47 UTC by honno

Adds a special case for the two functions that any NaNs present in computed elements should result in NaN. Hopefully I've used the correct language here.

Per discussion with @kgryte, this is expected behaviour. Do note this does mean PyTorch is wrong.
```python
>>> min([0., float("nan")])
0.0
>>> np.min(np.asarray([0., float("nan")]))
nan
>>> torch.min(torch.as_tensor([0., float("nan")]))
tensor(nan)
```

2021-11-15 11:36 UTC, rgommers commented
> Do note this does mean PyTorch is wrong.

I don't see that in the example. `tensor(nan)` (as a 0-D array) looks like the expected answer to me (reduction over 1-D array -> 0-D array). The `numpy.array_api` answer should match that, but it may not (?).

2021-11-15 11:39 UTC, honno commented
> > Do note this does mean PyTorch is wrong.
> 
> I don't see that in the example. `tensor(nan)` (as a 0-D array) looks like the expected answer to me (reduction over 1-D array -> 0-D array). The `numpy.array_api` answer should match that, but it may not (?).

Oops I was thinking of a different discussion (I didn't even read my own example, oops!)

2021-11-15 12:27 UTC, honno commented
@kgryte I suppose this special case applies to all statistical functions? If that's the case, I can update this PR.

2021-11-15 22:30 UTC, kgryte requested changes

2021-11-15 22:30 UTC, kgryte commented on spec/API_specification/statistical_functions.md
> +-   if `NaN` in elements over which to compute the maximum value, the result is `NaN`.
```suggestion
Let `x_i` be an element over which to compute the maximum value. For floating-point operands,

-   if `x_i` is `NaN`, the maximum value is `NaN` (i.e., `NaN` values propagate).
```

2021-11-15 22:30 UTC, kgryte commented on spec/API_specification/statistical_functions.md
> +-   if `NaN` in elements over which to compute the minimum value, the result is `NaN`.
Same changes as proposed above, except `s/maximum/minimum`.

2021-11-15 22:30 UTC, kgryte commented
@honno Yes, that is correct. `NaN` values should propagate for the other statistical functions. Feel free to update this PR. Thanks!

2021-12-06 18:22 UTC, kgryte approved these changes
LGTM. Thanks, @honno!

2021-12-06 18:27 UTC, merged