Clarify flattening behavior and fix required output shape for inverse indices in `unique_*` APIs
data-apis/array-api pull request #700
Opened 2023-11-06 05:09 UTC by kgryte

This PR

- resolves https://github.com/data-apis/array-api/issues/588 by clarifying flattening behavior and fixing the required output shape for returned inverse indices.
- makes explicit in the draft specification that flattening should be in row-major, C-style order. This is not backported to prior revisions. While this flattening behavior may have been assumed at the time of writing the specifications, we shouldn't be post-writing this assumption into prior revisions. Instead, we clarify expected behavior going forward. A strict reading of the prior revisions by downstream consumers should entail no guarantees regarding flattening order.
- makes explicit in the draft specification that the count order should match the order in `values` (i.e., the returned array of unique values). This was not made explicit in prior revisions, and its omission might indicate that `counts` could be returned in any order. While unlikely, we prohibit arbitrary count order for subsequent revisions.
- backports the following changes to the 2021 and 2022 revisions of the Array API standard:
    - correction to the required output shape of `inverse_indices`. Prior revisions stated that this should have the same shape as `x`, but this is only true if `x` is one-dimensional. For multi-dimensional `x`, the output shape should the shape of a flattened `x`.
    - clarifications regarding the contents of returned indices (first occurrences). Namely, that the returned array should include indices into a flattened `x`. For the case where `x` is one-dimensional, the guidance is the same. For multi-dimensional `x`, this clarifies that returned indices are for the flattened `x` and not the original input array.

2023-11-06 05:09 UTC, kgryte commented
@asmeurer Would you mind reviewing since you submitted the original issue? Thanks!

2024-01-11 21:52 UTC, rgommers commented
Eh, now seeing this right after NumPy changed it - consensus in the discussion that flattening was considered a bug, see https://github.com/numpy/numpy/pull/25553. I didn't really follow that PR, so let me ping @jakevdp here for his opinion on what to do with this.

2024-01-11 22:01 UTC, jakevdp commented
The goal of that PR was to make `np.unique_all` and `np.unique_inverse` compatible with the `2022.12` array API. After I sent the PR, reviewers suggested we change the output shape in `np.unique` as well.

For the array API, I think the current specification (i.e. not flattening `inverse_indices`) makes the most sense, because then you can always reconstruct the input using `unique_values[inverse_indices]`.

2024-01-12 01:08 UTC, leofang requested changes
(Mark it in red to avoid accidental merge.) So should we just close this PR now that NumPy devs also agreed we don't need flattening?

2024-02-12 01:48 UTC, leofang commented
Q: @kgryte it seems we can just close this PR?

2024-02-13 06:26 UTC, closed without merging

2024-02-13 06:26 UTC, kgryte commented
@leofang Yes, I will close and move the clarifications regarding flattening behavior to a new PR.