Add note that cross-kind comparisons are undefined
data-apis/array-api pull request #822
Opened 2024-07-15 22:01 UTC by asmeurer

Does the language here look OK? Should we add anything along the lines of "comparisons with promotable types should promote first" (so that the result is numerically correct)? 

Fixes #819.

2024-09-19 05:33 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) are undefined and thus implementation-dependent.
```

2024-09-19 05:33 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) are undefined and thus implementation-dependent.
```

2024-09-19 05:34 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) are undefined and thus implementation-dependent.
```

2024-09-19 05:35 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
           Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:37 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
```

I don't think we need this note for `invert`, as it is not a comparison operation.

2024-09-19 05:37 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +           Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
           Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:38 UTC, kgryte commented on src/array_api_stubs/_draft/array_object.py
> +        .. note::
This comment should be added to `__lt__` below.

2024-09-19 05:39 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:39 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:39 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:40 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:40 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:40 UTC, kgryte commented on src/array_api_stubs/_draft/elementwise_functions.py
> +       Comparisons of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```suggestion
       Comparison of arrays without a corresponding promotable data type (see :ref:`type-promotion`) is undefined and thus implementation-dependent.
```

2024-09-19 05:41 UTC, kgryte requested changes
The language looks okay to me. Left comments for a small grammar correction and the need to add a missing note. Once addressed, LGTM.

2024-09-19 19:01 UTC, asmeurer commented
Done

2024-10-22 13:53 UTC, fancidev commented
For my understanding, by “comparison of arrays without a corresponding promotable data type”, do you mean that there does not exist a type where both array are promotable to, or do you mean the array has a type that can no longer be promoted “further”? I’m asking because the reference issue involves an example of int64 vs uint64, for which both interpretations apply, so it doesn’t seem entirely clear to me.

2024-10-31 04:22 UTC, kgryte approved these changes
LGTM. Thanks, @asmeurer!

2024-10-31 04:46 UTC, kgryte commented
> Should we add anything along the lines of "comparisons with promotable types should promote first" (so that the result is numerically correct)?

I believe this is already implied, as, practically speaking, in order to perform comparison, promotion is necessary (e.g., as automatically happens when comparing a float and a double in C). If we later find that we need to make this more explicit, we can address in a follow-up PR.

2024-10-31 04:55 UTC, merged